[build]
  command = "cd frontend && npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://internal-hr-application-dllc.onrender.com"

[context.deploy-preview.environment]
  REACT_APP_BACKEND_URL = "https://internal-hr-application-dllc.onrender.com"

[context.branch-deploy.environment]
  REACT_APP_BACKEND_URL = "https://internal-hr-application-dllc.onrender.com"
